let suggestions = [
    'AICARDI-GOUTIERES SYNDROME 1',
 'AORTIC VALVE DISEASE 2',
 'AUTOINFLAMMATION, LIPODYSTROPHY, AND DERMATOSIS SYNDROME',
 'Abdominal Pain',
 'Abdominal bloating',
 'Abdominal discomfort',
 'Abnormal breathing',
 'Abnormal coordination',
 'Abnormal heart beat',
 'Abortion, Habitual',
 'Ache',
 'Acquired Immunodeficiency Syndrome',
 'Acquired disease',
 'Actual Inability To Taste',
 'Acute Pneumonia',
 'Acute contagious conjunctivitis',
 'Acute gastroenteritis',
 'Acute infectious disease',
 'Acute infectious lymphocytosis',
 'Acute lower respiratory tract infection',
 'Acute onset cough',
 'Acute onset fever',
 'Acute viral disease',
 'Adenosine deaminase deficiency',
 'Adenovirus Infections',
 'Adult Fanconi syndrome',
 'Adynamic bone disease',
 'Age related macular degeneration',
 'Agenesis of corpus callosum',
 'Ageusia',
 'Agitation',
 'Agonizing Pain',
 'Alcoholic ketoacidosis',
 'Aleutian Mink Disease',
 'Algoneurodystrophy',
 'Allergic disposition',
 'Allergy to eggs',
 'Alopecia',
 'Alpha trait thalassemia',
 'Altered sensation of skin',
 'Altitude Sickness',
 'Amelogenesis imperfecta nephrocalcinosis',
 'Amyotrophic Lateral Sclerosis, Sporadic',
 'Anaphylaxis (non medication)',
 'Anemia, Diamond-Blackfan',
 'Angle Closure Glaucoma',
 'Ankylosing spondylitis',
 'Anorexia',
 'Anosmia',
 'Anus Diseases',
 'Aplasia Cutis Congenita',
 'Arm Pain',
 'Arthralgia',
 'Arthritis',
 'Arthritis, Psoriatic',
 'Arthrogryposis renal dysfunction cholestasis syndrome',
 'Arthropathy',
 'Aspergilloma',
 'Asthenia',
 'Asthenopia',
 'Asthma',
 'Asthma attack',
 'Asymptomatic Diseases',
 'Ataxia Telangiectasia',
 'Athabaskan brainstem dysgenesis',
 'Atherosclerosis',
 'Aural pressure',
 'Autoimmune Diseases',
 'Autoimmune disease (systemic) NOS',
 'Autoimmune hemolytic anemia',
 'Axenfeld-Rieger syndrome',
 'BESTROPHINOPATHY, AUTOSOMAL RECESSIVE',
 'BODY ACHE',
 'BODY PAIN',
 'Back Pain',
 'Back symptoms/complaints',
 'Bacteremia',
 'Bacterial Infections',
 'Balkan Nephropathy',
 'Basilar-Type Migraine',
 'Benign paroxysmal positional vertigo',
 'Bilateral pneumonia',
 'Blackout - symptom',
 'Bleeding ulcer',
 'Blind Vision',
 'Blindness of one eye (disorder)',
 'Blood Coagulation Disorders',
 'Blood in stool',
 'Bloodshot eye',
 'Blue - symptom',
 'Blurred vision',
 'Bone Cysts, Aneurysmal',
 'Borderline Hypertension',
 'Brain Damage, Chronic',
 'Breath Holding',
 'Breath symptom',
 'Breathing abnormally deep',
 'Bronchiectasis',
 'Bronchiolitis Obliterans Organizing Pneumonia',
 'Bronchitis',
 'Bronchitis, Chronic',
 'Bronchopulmonary Dysplasia',
 'Brown oculocutaneous albinism',
 'Bubonic Plague',
 'Burning Mouth Syndrome',
 'Burning feet',
 'Burning mouth (sensation)',
 'Burning sensation',
 'Burning sensation in eye',
 'Burning sensation of leg',
 'Bursitis',
 'Bursitis of hip',
 'Buzzing in ear',
 'C/O - postviral syndrome',
 'CEREBELLAR ATAXIA, NEUROPATHY, AND VESTIBULAR AREFLEXIA SYNDROME',
 'CHEST BURNING PAIN OF',
 'CHEST PAIN, SHARP',
 'CONOTRUNCAL ANOMALY FACE SYNDROME',
 'Cachexia',
 'Cancer-Associated Retinopathy',
 'Cardiac Arrest',
 'Cardiomyopathies',
 'Cardiovascular Diseases',
 'Cardiovascular symptoms',
 'Carotid Artery Diseases',
 'Carpal Tunnel Syndrome',
 'Cat allergy (disorder)',
 'Catarrh',
 'Catch - Finding of sensory dimension of pain',
 'Cerebellar decompression injury',
 'Cerebrovascular accident',
 'Cheiro-oral syndrome',
 'Chest Pain',
 'Chest discomfort',
 'Chest pain on breathing',
 'Chest pressure',
 'Chest tightness',
 'Chickenpox',
 'Chikungunya virus infection',
 'Chills',
 'Cholestasis-edema syndrome, Norwegian type',
 'Chromosome 2q32-Q33 Deletion Syndrome',
 'Chronic Fatigue Syndrome',
 'Chronic Headache',
 'Chronic Kidney Diseases',
 'Chronic Obstructive Airway Disease',
 'Chronic articular rheumatism',
 'Chronic back pain',
 'Chronic disease',
 'Chronic lobular hepatitis',
 'Chronic otitis media',
 'Chronic venous insufficiency',
 'Chronically Ill',
 'Circadian Rhythm Disorders',
 'Circling gait',
 'Classical Lissencephaly',
 'Clouded consciousness',
 'Coffin-Siris syndrome',
 'Coinfection',
 'Cold intolerance',
 'Cold sweat',
 'Comatose',
 'Common Cold',
 'Common Migraine',
 'Communicable Diseases',
 'Communicable Diseases, Emerging',
 'Confluent and Reticulate Papillomatosis',
 'Congenital Thrombotic Thrombocytopenic Purpura',
 'Congenital leukocyte adherence deficiency',
 'Congestion of throat',
 'Congestive heart failure',
 'Conjunctivitis',
 'Connective Tissue Diseases',
 'Constipation',
 'Cor pulmonale',
 'Coronary Arteriosclerosis',
 'Coronary Occlusion',
 'Coronary heart disease',
 'Coronavirus Infections',
 'Cough with fever',
 'Coughing',
 'Cowpox',
 'Critical Illness',
 'Crohn Disease',
 'Curb',
 'Cyclic neutropenia',
 'Cystic Fibrosis',
 'Cystitis',
 'DANDY-WALKER MALFORMATION WITH MENTAL RETARDATION, BASAL GANGLIA DISEASE, AND SEIZURES',
 'Dandy-Walker Syndrome',
 'Death anxiety',
 'Decompression Sickness',
 'Decrease in appetite',
 'Decreased Libido',
 'Deep Vein Thrombosis',
 'Deficiency of glucose-6-phosphate dehydrogenase',
 'Degenerative polyarthritis',
 'Deglutition Disorders',
 'Dehydration',
 'Dementia, familial Danish',
 'Dengue Fever',
 'Dental caries',
 'Depressed - symptom',
 'Depressive Symptoms',
 'Dermatitis',
 'Dermatofibrosis lenticularis disseminata',
 'Dermatologic disorders',
 'Diabetes',
 'Diabetes Mellitus',
 'Diabetes Mellitus, Non-Insulin-Dependent',
 'Diabetic Autonomic Neuropathy',
 'Diabetic Retinopathy',
 'Diarrhea',
 'Diarrhea and vomiting, symptom',
 'Diarrhea, watery',
 'Difficulty sleeping',
 'Digestive System Disorders',
 'Digestive symptom',
 'Digitorenocerebral Syndrome',
 'Disease',
 'Disorder of face',
 'Disorder of head',
 'Dizziness',
 'Dry cough',
 'Dryness of eye',
 'Duane Retraction Syndrome',
 'Dwarfism',
 'Dysosmia',
 'Dysosteosclerosis',
 'Dyspepsia',
 'Dyspnea',
 'Dyspnea on exertion',
 'Dyssomnias',
 'Dystonia Disorders',
 'EXERTIONAL',
 'Ear symptom',
 'Earache',
 'Ectodermal Dysplasia, Hypohidrotic, Autosomal Recessive',
 'Edema Disease of Swine',
 'Edema of foot (finding)',
 'Ehlers-Danlos Syndrome',
 'Elliptocytosis, Hereditary',
 'Encephalitis',
 'Encephalomyelitis, Western Equine',
 'Encephalopathy, Bovine Spongiform',
 'Endometriosis',
 'Eosinophilia-Myalgia Syndrome',
 'Epilepsy',
 'Episodic ataxia type 1',
 'Epstein',
 'Equilibration disorder',
 'Equine laminitis',
 'Erectile dysfunction',
 'Eructation',
 'Erythema',
 'Erythema Multiforme',
 'Erythromelalgia',
 'Euthyroid Sick Syndromes',
 'Exanthema',
 'Excessive tearing',
 'Excruciating pain',
 'Exhaustion',
 'Eye Infections',
 'Failure of Tooth Eruption, Primary',
 'Familial Alzheimer Disease (FAD)',
 'Fatigue',
 'Fatigue - symptom',
 'Feeling Cold',
 'Feeling Sick',
 'Feeling despair',
 'Feeling feverish',
 'Feeling nervous',
 'Feeling of loss of feeling',
 'Feeling of lump in throat',
 'Feeling strange',
 'Feels hot',
 'Feline infectious peritonitis',
 'Feline urological syndrome',
 'Fever with chills',
 'Fibrillary glomerulonephritis',
 'Fibromyalgia',
 'Fish-Eye Disease',
 'Flare',
 'Flatulence',
 'Flushing',
 'Food Allergy',
 'Foramen Ovale, Patent',
 'Frontal headache',
 'Gait, Drop Foot',
 'Gasping for breath',
 'Gastritis',
 'Gastroesophageal reflux disease',
 'Gastroparesis',
 'General symptom',
 'Generalized fatigue',
 'Genital infection',
 'Geroderma osteodysplastica',
 'Gerstmann-Straussler-Scheinker Disease',
 'Giant Cell Arteritis',
 'Gigantism',
 'Gingival Diseases',
 'Glossalgia',
 'Goldberg-Shprintzen megacolon syndrome',
 'Gonorrhea',
 'Gout',
 'Gray Platelet Syndrome',
 'Gum Infection',
 'HEAD PRESSURE SENSATION',
 'HEART PROBLEM',
 'HIV Infections',
 'HIV-infection (AIDS/ARC)',
 'Halitosis',
 'Hamman-Rich syndrome',
 'Hand joint pain',
 'Hantavirus Infections',
 'Has tingling sensation',
 'Hashimoto Disease',
 'Hay fever',
 'Headache',
 'Headache Severe',
 'Hearing disability',
 'Heart Diseases',
 'Heart failure',
 'Heartburn',
 'Heartburn acidity',
 'Hematological Disease',
 'Hemorrhagic Fever, Ebola',
 'Hemorrhagic Fevers, Viral',
 'Hemorrhoids',
 'Henoch-Schoenlein Purpura',
 'Heparin-induced thrombocytopenia',
 'Hepatic Encephalopathy',
 'Hepatic methionine adenosyltransferase deficiency',
 'Hepatitis',
 'Hepatitis A',
 'Hepatitis B, Chronic',
 'Hepatitis C',
 'Hepatorenal Syndrome',
 'Hereditary Coproporphyria',
 'Hereditary Diseases',
 'Hereditary Multiple Exostoses',
 'Herpes',
 'Herpes Labialis',
 'Herpes zoster disease',
 'Herpesviridae Infections',
 'Hip pain',
 'Hoarseness',
 'Hot flushes',
 'Hunger',
 'Hybrid Resistance',
 'Hypercholesterolemia',
 'Hyperemesis Gravidarum',
 'Hyperextension',
 'Hyperkinetic Heart Syndrome',
 'Hyperostosis, Diffuse Idiopathic Skeletal',
 'Hypersensitivity disease',
 'Hypersomnia',
 'Hypertensive disease',
 'Hypotrichosis simplex',
 'IMMUNODEFICIENCY, COMMON VARIABLE, 10',
 'Idiopathic Multicentric Osteolyses',
 'Idiopathic peripheral neuropathy',
 'Illness (finding)',
 'Immune Complex Diseases',
 'Immune System Diseases',
 'Immunoglobulin A deficiency (disorder)',
 'Inclusion Body Myositis (disorder)',
 'Indifferent mood',
 'Infantile Neuroaxonal Dystrophy',
 'Infantile neuronal ceroid lipofuscinosis',
 'Infarction of spinal cord',
 'Infection of kidney',
 'Infection of tooth',
 'Infections, Hospital',
 'Infectious Mononucleosis',
 'Infectious disease of lung',
 'Inflammation of joint of foot',
 'Inflammatory disorder',
 'Influenza',
 'Influenza due to Influenza A virus subtype H1N1',
 'Influenza-like illness',
 'Influenza-like symptoms',
 'Interstitial emphysema',
 'Intestinal infectious disease (disorder)',
 'Irritable Bowel Syndrome',
 'Isaacs syndrome',
 'Itching of ear',
 'Jet Lag Syndrome',
 'Juvenile-Onset Still Disease',
 'Kartagener Syndrome',
 'Kidney Diseases',
 'Kidney Failure',
 'Kidney problem',
 'Klinefelter Syndrome',
 'LAURIN-SANDROW SYNDROME',
 'Labyrinthitis',
 'Laryngismus paralyticus',
 'Left sided chest pain',
 'Lesch-Nyhan Syndrome',
 'Lethargy',
 'Lichen Planus',
 'Lightheadedness',
 'Lip swelling',
 "Little's Disease",
 'Liver Abscess, Amebic',
 'Liver Cirrhosis',
 'Liver Failure, Acute',
 'Liver diseases',
 'Long QT Syndrome',
 'Loose stool',
 'Low Back Pain',
 'Lower Extremity Paresis',
 'Lower respiratory tract infection',
 'Lung Diseases, Interstitial',
 'Lung Diseases, Obstructive',
 'Lung Problem',
 'Lung diseases',
 'Lupus Erythematosus',
 'Lupus Erythematosus, Discoid',
 'Lyme Disease',
 'MAMMARY-DIGITAL-NAIL SYNDROME',
 'MICROCEPHALIC OSTEODYSPLASTIC PRIMORDIAL DWARFISM, TYPE I',
 'MOHR-TRANEBJAERG SYNDROME',
 'MRSA - Methicillin resistant Staphylococcus aureus infection',
 'MUNGAN SYNDROME',
 'Macrophage Activation Syndrome',
 'Macule',
 'Malaise',
 'Malaria',
 'Malaria, Cerebral',
 'Male Pseudohermaphroditism',
 'Malignant hyperpyrexia due to anesthesia',
 'Malnutrition',
 'Mandibuloacral dysostosis',
 'Mannose-Binding Protein Deficiency',
 'Marinesco-Sjogren syndrome',
 'Mass of body region',
 'Mastodynia',
 'McCune-Albright Syndrome',
 'Measles',
 'Meckel syndrome type 1',
 'Megaloblastic anemia due to inborn errors of metabolism',
 'Melnick-Needles Syndrome',
 'Memory Loss',
 'Meningitis',
 'Meningitis, Bacterial',
 'Meningococcal meningitis',
 'Mesenteric Panniculitis',
 'Metabolic Diseases',
 'Migraine Disorders',
 'Migraine Variant',
 'Mild chronic obstructive pulmonary disease',
 'Mitral Valve Prolapse Syndrome',
 'Morning headache',
 'Motion Sickness',
 'Mucocutaneous Lymph Node Syndrome',
 'Multi-infarct dementia',
 'Multiple Epiphyseal Dysplasia',
 'Multiple Sclerosis',
 'Multiple symptoms',
 'Mumps',
 'Muscle Cramp',
 'Muscle Rigidity',
 'Muscle Weakness',
 'Muscle twitch',
 'Muscular fasciculation',
 'Muscular stiffness',
 'Myalgia',
 'Myasthenia Gravis',
 'Myasthenia Gravis, Ocular',
 'Mycoses',
 'Myelitis',
 'Myelitis, Acute Transverse',
 'Myocardial Infarction',
 'Myocardial Ischemia',
 'Myopathy',
 'Myopia',
 'Myopic astigmatism',
 'Nail-Patella Syndrome',
 'Narcolepsy',
 'Nasal congestion (finding)',
 'Nausea',
 'Neck Pain',
 'Neonatal Jaundice',
 'Neonatal alloimmune thrombocytopenia',
 'Neonatal hemochromatosis',
 'Nephritis, Interstitial',
 'Nervousness',
 'Neuroleptic Malignant Syndrome',
 'Neurologic Symptoms',
 'Neuropathy',
 'Night sweats',
 'Nightmares',
 'Nocturnal cough',
 'Nodular glomerulosclerosis',
 'Nose symptoms',
 'Numbness',
 'Numbness of face',
 'Numbness of foot',
 'Obesity',
 'Occipital Lobe Epilepsy',
 'Oculocerebrocutaneous syndrome',
 'Optic Neuritis',
 'Oral Ulcer',
 'Osteochondritis Dissecans',
 'Osteoporosis',
 'Osteoporosis with pseudoglioma',
 'Other symptoms',
 'Other viral diseases NOS',
 'Overweight',
 'PHOTOPAROXYSMAL RESPONSE 1',
 'POPLITEAL PTERYGIUM SYNDROME, LETHAL TYPE',
 'PREMATURE CHROMATID SEPARATION TRAIT',
 'PROGRESSIVE ENCEPHALOMYELITIS WITH RIGIDITY',
 'Pain',
 'Pain in buttock',
 'Pain in calf',
 'Pain in left shoulder',
 'Pain in right hand',
 'Pain of lymph node',
 'Pain, Burning',
 'Pain, Postoperative',
 'Painful Bladder Syndrome',
 'Pallister-Hall syndrome',
 'Palmar-plantar erythrodysesthesia syndrome',
 'Pancreatic Pseudocyst',
 'Pancreatitis',
 'Papillon-Lefevre Disease',
 'Paracoccidioidomycosis',
 'Paramyotonia Congenita (disorder)',
 'Paraneoplastic Opsoclonus Ataxia',
 'Paresis',
 'Paresthesia of hand',
 'Parkinson Disease',
 'Parkinsonian Disorders',
 'Pelvic Organ Prolapse',
 'Pelvic Pain',
 'Pemphigus and fogo selvagem',
 'Pentalogy of Cantrell',
 'Perceived quality of life',
 'Periodic Alternating Nystagmus',
 'Peripheral Neuropathy',
 'Peripheral Vascular Diseases',
 'Pertussis',
 'Pharyngeal dryness',
 'Pharyngitis',
 'Phlebitis',
 'Phlebotomus Fever',
 'Photopsia',
 'Pins and needles',
 'Pityriasis Rosea',
 'Plague',
 'Plague, Septicemic',
 'Pleurisy',
 'Pneumocystis jiroveci pneumonia',
 'Pneumonia',
 'Pneumonia, Bacterial',
 'Pneumonia, Viral',
 'Pneumopericardium',
 'Poliomyelitis',
 'Polyarteritis Nodosa',
 'Polyglandular Type I Autoimmune Syndrome',
 'Polymyalgia Rheumatica',
 'Post-infectious encephalitis',
 'Posterior reversible encephalopathy syndrome',
 'Posterior rhinorrhea',
 'Postural Orthostatic Tachycardia Syndrome',
 'Potassium aggravated myotonia',
 'Prediabetes syndrome',
 'Preeclamptic toxemia',
 'Premenopausal symptoms',
 'Premenstrual syndrome',
 'Prickling sensation',
 'Prieto X-linked mental retardation syndrome',
 'Primary Cough Headache',
 'Productive cough',
 'Prurigo',
 'Pruritus',
 'Pseudohypoparathyroidism',
 'Pseudohypoparathyroidism, Type Ia',
 'Psoriasis',
 'Pulmonary Alveolar Proteinosis',
 'Pulmonary Embolism',
 'Pulmonary Emphysema',
 'Pulmonary Fibrosis',
 'Pulmonary Stenosis',
 'Pulmonary congestion',
 'Punctate inner choroidopathy',
 'Purpura pigmentosa chronica',
 'Pyotraumatic dermatitis',
 'RAINE SYNDROME',
 'Radiation Damage',
 'Rales',
 'Rare Diseases',
 'Recurrent abdominal pain',
 'Recurrent disease',
 'Redness of eye',
 'Redness of face',
 'Reflex Epilepsy, Photosensitive',
 'Reflex Epilepsy, Reading',
 'Reflex Sympathetic Dystrophy',
 'Refractive Errors',
 'Renal carnitine transport defect',
 'Renal pain',
 'Respiration Disorders',
 'Respiratory Distress Syndrome, Adult',
 'Respiratory Failure',
 'Respiratory Tract Infections',
 'Respiratory distress',
 'Respiratory problems',
 'Restless Legs Syndrome',
 'Retching',
 'Retinal damage',
 'Rheumatoid Arthritis',
 'Rhinorrhea',
 'Rib pain',
 'Right Flank Pain',
 'Roberts-SC phocomelia syndrome',
 'Robinow syndrome, autosomal recessive',
 'Rolling of eyes',
 'Rosacea',
 'Rubella',
 'SHORT STATURE, IDIOPATHIC, X-LINKED',
 'SHORT STATURE, ONYCHODYSPLASIA, FACIAL DYSMORPHISM, AND HYPOTRICHOSIS SYNDROME',
 'SHOULDER TENDERNESS',
 'STOMATOCYTOSIS I',
 'STUVE-WIEDEMANN SYNDROME',
 'Scarlet Fever',
 'Sciatica',
 'Scurvy',
 'Secondary Infections',
 'Secondary bacterial pneumonia',
 'Seizures',
 'Sensation of warmth',
 'Sensorineural Hearing Loss (disorder)',
 'Sensory Discomfort',
 'Sepsis',
 'Septicemia',
 'Severe Acute Respiratory Syndrome',
 'Severe Combined Immunodeficiency',
 'Severe chronic obstructive pulmonary disease',
 'Severe diarrhea',
 'Severe pain',
 'Sexually Transmitted Diseases',
 'Shaking of hands',
 'Sharp pain',
 'Shoulder Pain',
 'Shoulder stiff',
 'Sick Sinus Syndrome',
 'Sighing respiration',
 'Signs and Symptoms',
 'Signs and Symptoms, Respiratory',
 'Simian Acquired Immunodeficiency Syndrome',
 'Single organ dysfunction',
 'Sinus Tachycardia',
 'Sinus pain',
 'Sinusitis',
 'Sjogren-Larsson Syndrome',
 'Skin Diseases, Infectious',
 'Skin Diseases, Viral',
 'Skin lesion',
 'Skin symptom',
 'Sleep Apnea Syndromes',
 'Sleep Starts',
 'Sleep disturbances',
 'Sleeplessness',
 'Slow respiration',
 'Small Fiber Neuropathy',
 'Smallpox',
 'Somnambulism',
 'Sore Throat',
 'Sore eye',
 'Sore mouth',
 'Sore skin',
 'Sore to touch',
 'Spasm',
 'Spasmodic movement',
 'Spastic syndrome',
 'Specific viral infections',
 'Spondyloepiphyseal dysplasia, Omani type',
 'Staphylococcal Infections',
 'Staphylococcus aureus infection',
 'Staring',
 'Steroid-induced myopathy',
 'Stiffness',
 'Stinging Sensation',
 'Stomach ache',
 'Stomach cramps (finding)',
 'Strabismus',
 'Strangles',
 'Streptococcal Infections',
 'Streptococcal lymphadenitis of swine',
 'Streptococcal sore throat',
 'Struck',
 'Subacute thyroiditis',
 'Sudden infant death syndrome',
 'Suffocated',
 'Symmetrical dyschromatosis of extremities',
 'Sympathetically independent pain',
 'Symptom Flare Up',
 'Syncope',
 'Syncope, Cardiogenic',
 'Syndrome',
 'Syphilis',
 'Tachycardia, Ectopic Junctional',
 'Temporal headache',
 'Temporohyoid osteoarthropathy',
 'Tenalgia',
 'Tennis Elbow',
 'Tension Headache',
 'Terminal illness',
 'Testicular regression syndrome',
 'Tetanus',
 'Throat irritation',
 'Throat symptom',
 'Throbbing Headache',
 'Thromboembolism',
 'Thrombophilia',
 'Thyroid Diseases',
 "Tietze's Syndrome",
 'Tired',
 'Tonsillitis',
 'Toothache',
 'Total Hypotrichosis, Mari type',
 'Toxic Shock Syndrome',
 'Toxic liver disease',
 'Transient Ischemic Attack',
 'Tremor',
 'Trigger Finger Disorder',
 'Triglyceride storage disease with ichthyosis',
 'Tropical Disease',
 'Tropical Spastic Paraparesis',
 'Tuberculosis',
 'Tuberculous otitis media',
 'Tumor Necrosis Factor Receptor 1-Associated Periodic Syndrome',
 'Ulnar-mammary syndrome',
 'Upper Extremity Paresis',
 'Upper Respiratory Infections',
 'Upper back pain',
 'Upset stomach',
 'Urinary tract infection',
 'Urticaria',
 'Urticaria Pigmentosa',
 'Vaccines allergy',
 'Vaccinia',
 'Vague ill health',
 'Van der Woude syndrome',
 'Vascular Diseases',
 'Vasculitis',
 'Verbal auditory hallucinations',
 'Vertigo',
 'Vesicle (morphologic abnormality)',
 'Vestibular Diseases',
 'Viral exanthem',
 'Viral myocarditis',
 'Virus Diseases',
 'Visual disturbance',
 'Visual halos (disorder)',
 'Vitamin D Deficiency',
 'Vitamin Deficiency',
 'Vitelliform Macular Dystrophy',
 'Vomiting',
 'WILSON-TURNER X-LINKED MENTAL RETARDATION SYNDROME',
 'Walking pneumonia',
 'Wasting',
 'Watery eyes',
 'Weakness',
 'Weight symptom (finding)',
 'Welts',
 'West Nile viral infection',
 'Wheezing',
 'Wiskott-Aldrich Syndrome',
 'Withdrawal Symptoms',
 'Wolf-Hirschhorn Syndrome',
 'Xerostomia',
 'Zunich neuroectodermal syndrome',
 'asthma with copd',
 'bowel discomfort',
 'charmed',
 'chest burning',
 'chest heaviness',
 'clogged ear',
 'cold symptoms',
 'digestive problem',
 'dyspnea acute',
 'feeling dizzy',
 'feeling like vomiting',
 'flu symptoms',
 'furuncle',
 'gastrointestinal gas',
 'hand rash',
 'headache migraine chronic',
 'headache severe',
 'heart inflammation',
 'herpes',
 'impending doom',
 'local reaction',
 'lump in throat',
 'microbial disease',
 'mitral annulus calcification',
 'multiple pathologies',
 'nasal itching',
 'neck tightness',
 'organic disorders',
 'out (of) breath',
 'panic symptoms',
 'persistent dry cough',
 'physical disorders',
 'physical symptom',
 'pneumonia clinical',
 'post viral fatigue',
 'prickly feeling',
 'primary infection nos',
 'red blotches',
 'reproductive system disorder',
 'room spinning',
 'rundown',
 'shock symptoms',
 'sick to stomach',
 'side pain',
 'skin color change',
 'skin damage',
 'slight fever',
 'spells (neurological symptom)',
 'swollen glands in neck',
 'symptoms, signs, and ill-defined conditions',
 'taste salty',
 'taste sour',
 'taste sweet',
 'tingling in fingers',
 'underlying infection',
 'varicella zoster'
];